name: learn-github-actions
on:
  issues:
    types: [opened, edited]

jobs:
  auto_label:
    runs-on: ubuntu-latest
    name: Automatic Github Issue Labeller
    steps:
    - name: Label Step
      uses: larrylawl/Auto-Github-Issue-Labeller@main
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        REPOSITORY: 'ishitachawla/Playlist,ishitachawla/Label-testing'
        DELTA: "1"
        CONFIDENCE: "2"
        FEATURE: "enhancement"
        BUG: "bug"
        DOCS: "documentation"
        VERSION: "v1.0"
      
